### PR TITLE
gui: use sets for `in` membership testing

### PR DESCRIPTION
**Pull request by bkazemi**
It is faster to use sets over lists for this (sets are O(1) while
lists are O(n)).

### CODE REVIEW

**Comment by 12345ieee** [comment]
Yeah, sure, for what's worth optimizing a linear search in an array long 7.
I'd really like to get #176 in before anything else related to the gui, though, hopefully it won't break anything here.

**Comment by bkazemi** [comment]
Well, yeah, it's not that big a difference, but it never hurts to shave off a few cycles when the change is this trivial. And because the changes are so trivial, if this were to conflict with #176 I could just quickly adjust it.

So note to @sriemer not to commit this before #176 in case.

**Comment by 12345ieee** [comment]
I was looking at it, #176 touches nothing of this, but it introduces another `thing in things` that you'll want to make a set.

**Comment by bkazemi** [comment]
Oh, great. Even so, it would still make sense to commit #176 before this so I could push the change to the new `thing in things` in this PR.

**Comment by sriemer** [comment]
Alright, testing + merging after #176.

**Comment by bkazemi** [comment]
Sorry, I forgot to put this under a separate branch and unwittingly closed this by force pulling master. I'll re-do this PR.

**Comment by sriemer** [comment]
I've seen merge commits in my e-mail notification regarding this. Please don't use `git pull` if changes are not fast-forward. Use `git rebase upstream/master` instead to follow upstream commits. Of cause you should set up an upstream remote to scanmem/scanmem.

**Comment by bkazemi** [comment]
Okay, noted. Thanks

**Pull request closed without merging**
