### PR TITLE
Fixup for ba6d473781838846908d459d5c8272a69a2a0f42 broken gui make

### PR DESCRIPTION
**Pull request by shenada**
3a7f11991b9794a16e9dc0fe01b2ec34027312fa

### CODE REVIEW

**Comment by 12345ieee** [comment]
Ouch, thanks for that first commit, I forgot we declare the py sources in the Makefile.
I'll merge it immediately to fix the build, then we can review the rest with ease.

**Comment by shenada** [comment]
Sorry, Not full branch...
Just 3a7f119

BTW, Any git formatpatch/am equivalent on github ?

**Comment by 12345ieee** [comment]
I took only that anyway.
If that was the only commit you wanted to PR we can just close this.

To prepare a "patch" the easiest way is to make a branch that is based on master and has all the commits you want (and only those) and open a PR with that.

**Comment by shenada** [comment]
61f5a75 need your review.

**Comment by shenada** [comment]
346de29 Not sure why Monospace font has different pango layout width between dig & chr

**Pull request closed without merging**
