### PR TITLE
fix enable/with arguments in configure.ac

### PR DESCRIPTION
**Pull request by coolwanglu**
fix enable/with arguments in configure.ac; renames libreplacements* to readline*

### CODE REVIEW

**Comment by sriemer** [comment]
Thanks! Assigning to me for review. I'll look into this ASAP.

**Comment by Funmungus** [comment]
I also just noticed the strange function definitions I put in readline.c.  Sorry I did not look closely enough at that.

**Comment by sriemer** [comment]
LGTM. Thank you very much for cleaning this up!

**Comment by sriemer** [comment]
I'm rebasing my branches to latest upstream. All others should do so as well now. I'm e.g. working on FreeBSD support. I know an IT security professional who would really love having scanmem there.

**Pull request merged**
