### PR TITLE
Update the appdata to metainfo

### LINKED ISSUE #295: Lintian complains about legacy format in GameConqueror.appdata.xml
```
W: gameconqueror: appstream-metadata-in-legacy-location usr/share/appdata/GameConqueror.appdata.xml
E: gameconqueror: appstream-metadata-legacy-format usr/share/appdata/GameConqueror.appdata.xml
```

See: https://lintian.debian.org/tags/appstream-metadata-legacy-format.html

Blocks Debian packaging for #288.

### PR DESCRIPTION
**Pull request by sriemer**
Just fix #295.

### CODE REVIEW

**Comment by sriemer** [comment]
@ignatenkobrain: I'm sure this one is interesting for you as well and this one is interesting for other distros in #288.

**Comment by sriemer** [comment]
Okay, then my vote is for id `org.scanmem.gameconqueror` if we use non-existing domains. Is that fine for you?

**Comment by 12345ieee** [comment]
@sriemer , that's ok for me.

Considering that @kartikm uploaded to unstable earlier today (see https://tracker.debian.org/news/902673 ) I wonder if now we are committed to the initial name.

**Comment by sriemer** [comment]
Nope, can do a 0.17-2.

**Comment by 12345ieee** [comment]
Good, let's go with `org.scanmem` as you said.
Update the PR and we can merge it.

**Comment by 12345ieee** [comment]
Many thanks for this PR.

I just noticed the policy is still called `org.freedesktop`, I guess we should change that as well, for consistency.

**Comment by sriemer** [comment]
Yes, but that can be done for `v0.18`. I don't want to risk regressions for `v0.17.x` in this regard right now.

**Comment by 12345ieee** [comment]
Makes sense.

I'll open an issue later to remind us.

**Pull request merged**
