### PR TITLE
scanmem: centralize messaging

### PR DESCRIPTION
**Pull request by bkazemi**
Also:
* Remove an unnecessary include.

### CODE REVIEW

**Comment by 12345ieee** [comment]
Agh, that's not what I meant! Arguably I should have written it better.

I wanted to change every mention of `printf/fprintf/other_stuff that writes to console`, like https://github.com/scanmem/scanmem/blob/c899ac335c479680ab2980dc62b9a73db699dcde/handlers.c#L1176
to an appropriate `show_something()`.

Fow example I wanted some variant of `show_in_parser()`, so that the parser-getting code could be moved to `show_message`.

About the change made in this PR, I'm not a huge fan of it, same logic but more verbose.

**Comment by bkazemi** [comment]
Fixed. I didn't change the `printf()` functions because data sent to `stdout` is different than "messages" sent to `stderr`.

**Comment by 12345ieee** [comment]
Sorry for disappearing for a while, between OS issues and Easter I was pretty busy.

I thought about it a bit, and as I said in chat, we really can't centralize calling the pager as much as I'd have liked, because you need full control on opening and closure.

So, I'll probably go for a much smaller patch that just moves the pager stuff in `show_message`.

I'm uncertain about `show_all()`, at this point it's probably clearer to show the full `fprintf(stderr,` given that we can't move everything to `show_*`.

I've pushed directly to your branch, @bkazemi , feel free to squash/modify as you see fit.

It should also be possible to remove some includes from `handlers.c` now, I leave that to you.

**Comment by bkazemi** [comment]
Updated.

**Comment by 12345ieee** [comment]
Thanks, and sorry for having you rewrite it twice.

Merging.

**Pull request closed without merging**
