### PR TITLE
Accelerators and build fix

### PR DESCRIPTION
**Pull request by calculuswhiz**
1. Adds accelerators for existing functionality:
   - CTRL+F: Opens Process selection window
   - CTRL+K: Focuses Search box
   - CTRL+<enter>: Begin search
   - CTRL+R: Reset search
   - CTRL+O: Open saved cheats
   - CTRL+S: Save current cheats
2. Integrated info about above accelerators into tooltips.
3. Fixes a build bug with the .po files with newlines.

### CODE REVIEW

**Comment by 12345ieee** [comment]
I'm going to test this, thanks.

I had already found the .po problem and I fixed it in another commit (that has not been merged yet), we'll just fix it in whatever one gets merged first.

You did something wrong with .po regeneration, because your changed strings didn't change in the .po files.

**Comment by 12345ieee** [comment]
Can confirm it works, some points:

* Either don't touch the po's at all in this PR, or rebuild them via `cd ../po; intltool-update --report`
* I'd prefer `L` for the search bar, though it's debatable
* 3 buttons were left out:
    * `D`? for delete all?
    * `M`? for manually add?
    * No idea for mem editor
* While we are at it, `Ctrl+W` to close any active dialog would be cool

**Comment by calculuswhiz** [comment]
- Sure. I'll just do the rebuild as well since it seems to be an easy step. Redundancy is good.
- How about both? (`K` and `L`)
- I was just putting a few out there. I can add the others.
    - `D` and `M` sound good.
    - `CTRL+SHIFT+M`? How's that?
- Active dialogs? Does that mean any window that's not the main? I can do that, but escape already works for everything except the memory editor. Did you just want the memory editor?

**Comment by 12345ieee** [comment]
* Thanks. I'll get some merge conflicts, but that's not a problem.
* Approved.
* Approved again.
* Good call with Esc. I still think Ctrl+W should close any subwindow, but definitely add it to the memeditor.

**Comment by 12345ieee** [comment]
Thank you for the improvements.

I'm not a fan of the mem editor close button, though (I think of the mem editor as if it was one of the lateral bars of GIMP, like the tools one).

At least, put it on the right side of the interface (look at how it's done on the main window) or put 2 pixels of spacing from the other button.

**Comment by calculuswhiz** [comment]
Aye, I'll move the close button. I needed it as an easy way to call the callback function unfortunately.

Did I fix the .po issue at least?

**Comment by 12345ieee** [comment]
> Aye, I'll move the close button. I needed it as an easy way to call the callback function unfortunately.
Thanks.

> Did I fix the .po issue at least?
Nearly, you should run that command as the last thing before you commit.

Though there are fuzzy fixes that'll need to be done manually anyway, we'll see when we merge this.

**Comment by calculuswhiz** [comment]
I need to rebuild the .po every time I commit?

**Comment by 12345ieee** [comment]
Not really, I rebuild them once in a while, when I do a lot of string changes.
Your PR qualifies as "a lot of string changes".

Don't bother too much with it, we'll have to fix them up anyway.

**Comment by calculuswhiz** [comment]
That should be it for major changes. Oh, and on that process search window, should that "CTRL+F to search for a process" title still be there?

**Comment by 12345ieee** [comment]
@calculuswhiz I'm very, very reluctant in recommending this, I'm actually using a branch ~25 commits in the future: 12345ieee/scanmem@next , where I fixed the bugs you keep noticing (and a ton more you didn't notice), you could base your work on it to avoid doubling up on what I already did.

I am waiting for @sriemer to review and merge the first block of it in #194 .

Upsides:
* You use a basically beta version, if you are into it
* More bugs are fixed
* Even more bugs are waiting to be caught by another pair of eyes

Downsides:
* @sriemer hasn't reviewed it, you have to trust me
* If you build on it, you have to tell me, as I rebase it often, I'll find a better arrangement
* Not everything there might make it to the official repo

**Comment by calculuswhiz** [comment]
Yeah, sure I'm game for that. Should I just pull and install from yours then? What will happen to these PR's?

**Comment by 12345ieee** [comment]
I think I'll put my branch under the official scanmem repo (tomorrow, it's late here), so that you don't need to track an extra remote.
I'll also promise I won't rebase it.

As for the PR, it's better to wait for @sriemer 's opinion.

**Comment by calculuswhiz** [comment]
Ok. I think I'll wait until he gets around to it then before I touch anything else. Thank you.

**Comment by 12345ieee** [comment]
I pushed my branch on the main repo, as `gui-next` (as I discussed with @sriemer previously).
I tested it, and I can merge pull requests on that branch (and generally push on it).

As such, I'll start accepting and merging gui-related PRs based on it.

This will hopefully allow the gui development to proceed at an appropriate pace, without having PRs that block each other ( #188 is another example).

Then @sriemer can merge and test at his leisure, to assure code is ready for `master`.

As such, you can rebase your PR on that branch if you want, you'll see you have another label to set an Alt key for and some other changes.

**Comment by calculuswhiz** [comment]
Did it work? This is my first time rebasing something ever, so please tell me.

**Comment by sriemer** [comment]
Commits should be reworked. If there is a .po build problem in the current master branch, then I want to have a separate commit for this. Code should be split from po changes for bigger changes. The first commit is unatomic.

WTF is the commit "Rebase attempt"?

Please close this PR, develop on top of the branch from @12345ieee  and create a PR for `scanmem:gui-next` instead.

**Comment by 12345ieee** [comment]
@calculuswhiz , you did everything right, the branch is correctly rebased.

Now this PR needs to be closed and reopened against `gui-next`, same thing that was done in #209 .
I'll review it once it's reopened.

@sriemer , the .po issues are now handled in gui-next, at e2f4da599b050cea9598547afbb3876044d1c1ab , while I edited the very same string for other reasons, I also removed the extra newlines.

If you need that commit broken up, just ask.

Closing this, waiting for @calculuswhiz .

**Pull request closed without merging**
