### PR TITLE
gui: use sets for `in` membership testing

### PR DESCRIPTION
**Pull request by bkazemi**
It is faster to use sets over lists for this (sets are O(1) while
lists are O(n)).

### CODE REVIEW

**Comment by 12345ieee** [comment]
You forgot a couple of `pressedkey in ('Delete', 'BackSpace'):`

**Comment by bkazemi** [comment]
I think those were committed after I opened the original PR. This branch seemed to be out of wack when I rebased, so I had to force commit. Do you want me to squash these commits?

**Comment by 12345ieee** [comment]
Yep, squash them in just one commit with a good message and I'll merge this.

Thanks for the contribution.

**Comment by bkazemi** [comment]
Alright, squashed with a slightly more descriptive commit message.

**Pull request merged**
