### PR TITLE
gui: Fix incorrect resize bug

### LINKED ISSUE #74: gui: resizing works incorrectly
```
try to resize window

it just moving... take a look for video
```

Original issue reported on code.google.com by `i.gnaten...@gmail.com` on 16 Jun 2014 at 5:25

Attachments:
* [Screencast from 06-16-2014 09:24:29 PM.webm](https://storage.googleapis.com/google-code-attachments/scanmem/issue-74/comment-0/Screencast from 06-16-2014 09:24:29 PM.webm)

### PR DESCRIPTION
**Pull request by 12345ieee**
Discovered the culprit by chance while doing a complete rehauling of the gtk containers (I'll open a PR for that, too, when ready).

Probably the most impressive bug I've ever fixed in only 7 characters.

Fixes #74 .

### CODE REVIEW

**Comment by sriemer** [comment]
Really? That simple? I'll test that. Thanks!

**Comment by sriemer** [comment]
To be honest, I don't see any difference with GTK 3.16. Does it only affect more recent GTK versions?

**Comment by sriemer** [comment]
For me it is much more annoying that the block with the search prompt is left aligned and the results list is not getting longer. Furthermore, if putting the Window too small I get:
````
*** BUG ***
In pixman_region32_init_rect: Invalid rectangle passed
Set a breakpoint on '_pixman_log_error' to debug
````

I think limits for the size should be set and full-screen should be forbidden.

**Comment by 12345ieee** [comment]
Can you test the end result of #176 and see if you still have bugs/things you want changed?

**Comment by 12345ieee** [comment]
#74 has been fixed by commit  ae7913a , which contains the change here.
So closing.

**Pull request closed without merging**
